modName=DynamicTreesTheTwilightForest
modId=dttwilightforest
modVersion=2.2.0
group=com.maxhyper.dttwilightforest

mcVersion=1.21.1
neoForgeVersion=21.1.234
mappingsVersion=2024.11.17

dynamicTreesFileId=8227322
dynamicTreesPlusVersion=1.3.2
twilightForestFileId=7797302

curseFileType=release
curseProjectId=391986
updateCheckerPath=Add-ons/TheTwilightForest.json

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
