modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees-TheTwilightForest/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/TheTwilightForest.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-the-twilight-forest"

authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.dttwilightforest]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.dttwilightforest]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.dttwilightforest]]
modId="dynamictrees"
type="required"
versionRange="[${dynamic_trees_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.dttwilightforest]]
modId="dynamictreesplus"
type="optional"
versionRange="[${dynamic_trees_plus_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.dttwilightforest]]
modId="twilightforest"
type="required"
versionRange="[${twilight_forest_version},)"
ordering="AFTER"
side="BOTH"
